apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: client-app
  name: client-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client-app
    spec:
      containers:
      - args:
        - python
        - app.py
        env:
        - name: FLASK_RUN_PORT
          value: "5000"
        image: arei2701/proiect-idp:client-app
        name: client-app
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
