version: "3"

services:
  client-app:
    build: ./client-app
    command: python -u app.py
    image: arei2701/proiect-idp:client-app
    networks:
      - front-tier
      - back-tier
    ports:
      - "5000:80"

  admin-app:
    build: ./admin-app
    image: arei2701/proiect-idp:admin-app
    command: python app.py
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "redis"

  manager-app:
    build: ./db_manager
    image: arei2701/proiect-idp:db-manager
    command: python app.py
    ports:
      - "5002:5002"
      - "5859:5859"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "db"
    environment:
      - FLASK_RUN_PORT=5002
    links:
      - db
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arei2701
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
