version: "3"

services:
  client-app:
    build: ./client-app
    command: python app.py
    image: arei2701/proiect-idp:client-app
    networks:
      - front-tier
      - back-tier
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_PORT=5000
    links:
      - admin-app
 
  manager-app:
    build: ./db_manager
    image: arei2701/proiect-idp:db-manager
    command: python app.py
    ports:
      - "5002:5002"
      - "5859:5859"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "db"
    environment:
      - FLASK_RUN_PORT=5002
    links:
      - db
      
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  admin-app:
    build: ./admin-app
    image: arei2701/proiect-idp:admin-app
    command: python app.py
    ports:
      - "5001:5001"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "redis"
    environment:
      - FLASK_RUN_PORT=5001
    links:
      - manager-app
     
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arei2701
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
